// Code generated by protoc-gen-go. DO NOT EDIT.
// source: osmformat.proto

package OSMPBF

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Relation_MemberType int32

const (
	Relation_NODE     Relation_MemberType = 0
	Relation_WAY      Relation_MemberType = 1
	Relation_RELATION Relation_MemberType = 2
)

var Relation_MemberType_name = map[int32]string{
	0: "NODE",
	1: "WAY",
	2: "RELATION",
}
var Relation_MemberType_value = map[string]int32{
	"NODE":     0,
	"WAY":      1,
	"RELATION": 2,
}

func (x Relation_MemberType) Enum() *Relation_MemberType {
	p := new(Relation_MemberType)
	*p = x
	return p
}
func (x Relation_MemberType) String() string {
	return proto.EnumName(Relation_MemberType_name, int32(x))
}
func (x *Relation_MemberType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Relation_MemberType_value, data, "Relation_MemberType")
	if err != nil {
		return err
	}
	*x = Relation_MemberType(value)
	return nil
}
func (Relation_MemberType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{11, 0}
}

type HeaderBlock struct {
	Bbox *HeaderBBox `protobuf:"bytes,1,opt,name=bbox" json:"bbox,omitempty"`
	// Additional tags to aid in parsing this dataset
	RequiredFeatures []string `protobuf:"bytes,4,rep,name=required_features,json=requiredFeatures" json:"required_features,omitempty"`
	OptionalFeatures []string `protobuf:"bytes,5,rep,name=optional_features,json=optionalFeatures" json:"optional_features,omitempty"`
	Writingprogram   *string  `protobuf:"bytes,16,opt,name=writingprogram" json:"writingprogram,omitempty"`
	Source           *string  `protobuf:"bytes,17,opt,name=source" json:"source,omitempty"`
	// replication timestamp, expressed in seconds since the epoch,
	// otherwise the same value as in the "timestamp=..." field
	// in the state.txt file used by Osmosis
	OsmosisReplicationTimestamp *int64 `protobuf:"varint,32,opt,name=osmosis_replication_timestamp,json=osmosisReplicationTimestamp" json:"osmosis_replication_timestamp,omitempty"`
	// replication sequence number (sequenceNumber in state.txt)
	OsmosisReplicationSequenceNumber *int64 `protobuf:"varint,33,opt,name=osmosis_replication_sequence_number,json=osmosisReplicationSequenceNumber" json:"osmosis_replication_sequence_number,omitempty"`
	// replication base URL (from Osmosis' configuration.txt file)
	OsmosisReplicationBaseUrl *string  `protobuf:"bytes,34,opt,name=osmosis_replication_base_url,json=osmosisReplicationBaseUrl" json:"osmosis_replication_base_url,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *HeaderBlock) Reset()         { *m = HeaderBlock{} }
func (m *HeaderBlock) String() string { return proto.CompactTextString(m) }
func (*HeaderBlock) ProtoMessage()    {}
func (*HeaderBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{0}
}
func (m *HeaderBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderBlock.Unmarshal(m, b)
}
func (m *HeaderBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderBlock.Marshal(b, m, deterministic)
}
func (dst *HeaderBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderBlock.Merge(dst, src)
}
func (m *HeaderBlock) XXX_Size() int {
	return xxx_messageInfo_HeaderBlock.Size(m)
}
func (m *HeaderBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderBlock.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderBlock proto.InternalMessageInfo

func (m *HeaderBlock) GetBbox() *HeaderBBox {
	if m != nil {
		return m.Bbox
	}
	return nil
}

func (m *HeaderBlock) GetRequiredFeatures() []string {
	if m != nil {
		return m.RequiredFeatures
	}
	return nil
}

func (m *HeaderBlock) GetOptionalFeatures() []string {
	if m != nil {
		return m.OptionalFeatures
	}
	return nil
}

func (m *HeaderBlock) GetWritingprogram() string {
	if m != nil && m.Writingprogram != nil {
		return *m.Writingprogram
	}
	return ""
}

func (m *HeaderBlock) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *HeaderBlock) GetOsmosisReplicationTimestamp() int64 {
	if m != nil && m.OsmosisReplicationTimestamp != nil {
		return *m.OsmosisReplicationTimestamp
	}
	return 0
}

func (m *HeaderBlock) GetOsmosisReplicationSequenceNumber() int64 {
	if m != nil && m.OsmosisReplicationSequenceNumber != nil {
		return *m.OsmosisReplicationSequenceNumber
	}
	return 0
}

func (m *HeaderBlock) GetOsmosisReplicationBaseUrl() string {
	if m != nil && m.OsmosisReplicationBaseUrl != nil {
		return *m.OsmosisReplicationBaseUrl
	}
	return ""
}

type HeaderBBox struct {
	Left                 *int64   `protobuf:"zigzag64,1,req,name=left" json:"left,omitempty"`
	Right                *int64   `protobuf:"zigzag64,2,req,name=right" json:"right,omitempty"`
	Top                  *int64   `protobuf:"zigzag64,3,req,name=top" json:"top,omitempty"`
	Bottom               *int64   `protobuf:"zigzag64,4,req,name=bottom" json:"bottom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderBBox) Reset()         { *m = HeaderBBox{} }
func (m *HeaderBBox) String() string { return proto.CompactTextString(m) }
func (*HeaderBBox) ProtoMessage()    {}
func (*HeaderBBox) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{1}
}
func (m *HeaderBBox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderBBox.Unmarshal(m, b)
}
func (m *HeaderBBox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderBBox.Marshal(b, m, deterministic)
}
func (dst *HeaderBBox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderBBox.Merge(dst, src)
}
func (m *HeaderBBox) XXX_Size() int {
	return xxx_messageInfo_HeaderBBox.Size(m)
}
func (m *HeaderBBox) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderBBox.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderBBox proto.InternalMessageInfo

func (m *HeaderBBox) GetLeft() int64 {
	if m != nil && m.Left != nil {
		return *m.Left
	}
	return 0
}

func (m *HeaderBBox) GetRight() int64 {
	if m != nil && m.Right != nil {
		return *m.Right
	}
	return 0
}

func (m *HeaderBBox) GetTop() int64 {
	if m != nil && m.Top != nil {
		return *m.Top
	}
	return 0
}

func (m *HeaderBBox) GetBottom() int64 {
	if m != nil && m.Bottom != nil {
		return *m.Bottom
	}
	return 0
}

type PrimitiveBlock struct {
	Stringtable    *StringTable      `protobuf:"bytes,1,req,name=stringtable" json:"stringtable,omitempty"`
	Primitivegroup []*PrimitiveGroup `protobuf:"bytes,2,rep,name=primitivegroup" json:"primitivegroup,omitempty"`
	// Granularity, units of nanodegrees, used to store coordinates in this block
	Granularity *int32 `protobuf:"varint,17,opt,name=granularity,def=100" json:"granularity,omitempty"`
	// Offset value between the output coordinates coordinates and the granularity grid in unites of nanodegrees.
	LatOffset *int64 `protobuf:"varint,19,opt,name=lat_offset,json=latOffset,def=0" json:"lat_offset,omitempty"`
	LonOffset *int64 `protobuf:"varint,20,opt,name=lon_offset,json=lonOffset,def=0" json:"lon_offset,omitempty"`
	// Granularity of dates, normally represented in units of milliseconds since the 1970 epoch.
	DateGranularity      *int32   `protobuf:"varint,18,opt,name=date_granularity,json=dateGranularity,def=1000" json:"date_granularity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveBlock) Reset()         { *m = PrimitiveBlock{} }
func (m *PrimitiveBlock) String() string { return proto.CompactTextString(m) }
func (*PrimitiveBlock) ProtoMessage()    {}
func (*PrimitiveBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{2}
}
func (m *PrimitiveBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveBlock.Unmarshal(m, b)
}
func (m *PrimitiveBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveBlock.Marshal(b, m, deterministic)
}
func (dst *PrimitiveBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveBlock.Merge(dst, src)
}
func (m *PrimitiveBlock) XXX_Size() int {
	return xxx_messageInfo_PrimitiveBlock.Size(m)
}
func (m *PrimitiveBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveBlock.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveBlock proto.InternalMessageInfo

const Default_PrimitiveBlock_Granularity int32 = 100
const Default_PrimitiveBlock_LatOffset int64 = 0
const Default_PrimitiveBlock_LonOffset int64 = 0
const Default_PrimitiveBlock_DateGranularity int32 = 1000

func (m *PrimitiveBlock) GetStringtable() *StringTable {
	if m != nil {
		return m.Stringtable
	}
	return nil
}

func (m *PrimitiveBlock) GetPrimitivegroup() []*PrimitiveGroup {
	if m != nil {
		return m.Primitivegroup
	}
	return nil
}

func (m *PrimitiveBlock) GetGranularity() int32 {
	if m != nil && m.Granularity != nil {
		return *m.Granularity
	}
	return Default_PrimitiveBlock_Granularity
}

func (m *PrimitiveBlock) GetLatOffset() int64 {
	if m != nil && m.LatOffset != nil {
		return *m.LatOffset
	}
	return Default_PrimitiveBlock_LatOffset
}

func (m *PrimitiveBlock) GetLonOffset() int64 {
	if m != nil && m.LonOffset != nil {
		return *m.LonOffset
	}
	return Default_PrimitiveBlock_LonOffset
}

func (m *PrimitiveBlock) GetDateGranularity() int32 {
	if m != nil && m.DateGranularity != nil {
		return *m.DateGranularity
	}
	return Default_PrimitiveBlock_DateGranularity
}

// Group of OSMPrimitives. All primitives in a group must be the same type.
type PrimitiveGroup struct {
	Nodes                []*Node      `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	Dense                *DenseNodes  `protobuf:"bytes,2,opt,name=dense" json:"dense,omitempty"`
	Ways                 []*Way       `protobuf:"bytes,3,rep,name=ways" json:"ways,omitempty"`
	Relations            []*Relation  `protobuf:"bytes,4,rep,name=relations" json:"relations,omitempty"`
	Changesets           []*ChangeSet `protobuf:"bytes,5,rep,name=changesets" json:"changesets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PrimitiveGroup) Reset()         { *m = PrimitiveGroup{} }
func (m *PrimitiveGroup) String() string { return proto.CompactTextString(m) }
func (*PrimitiveGroup) ProtoMessage()    {}
func (*PrimitiveGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{3}
}
func (m *PrimitiveGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveGroup.Unmarshal(m, b)
}
func (m *PrimitiveGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveGroup.Marshal(b, m, deterministic)
}
func (dst *PrimitiveGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveGroup.Merge(dst, src)
}
func (m *PrimitiveGroup) XXX_Size() int {
	return xxx_messageInfo_PrimitiveGroup.Size(m)
}
func (m *PrimitiveGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveGroup.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveGroup proto.InternalMessageInfo

func (m *PrimitiveGroup) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *PrimitiveGroup) GetDense() *DenseNodes {
	if m != nil {
		return m.Dense
	}
	return nil
}

func (m *PrimitiveGroup) GetWays() []*Way {
	if m != nil {
		return m.Ways
	}
	return nil
}

func (m *PrimitiveGroup) GetRelations() []*Relation {
	if m != nil {
		return m.Relations
	}
	return nil
}

func (m *PrimitiveGroup) GetChangesets() []*ChangeSet {
	if m != nil {
		return m.Changesets
	}
	return nil
}

// * String table, contains the common strings in each block.
//
// Note that we reserve index '0' as a delimiter, so the entry at that
// index in the table is ALWAYS blank and unused.
//
type StringTable struct {
	S                    [][]byte `protobuf:"bytes,1,rep,name=s" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringTable) Reset()         { *m = StringTable{} }
func (m *StringTable) String() string { return proto.CompactTextString(m) }
func (*StringTable) ProtoMessage()    {}
func (*StringTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{4}
}
func (m *StringTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringTable.Unmarshal(m, b)
}
func (m *StringTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringTable.Marshal(b, m, deterministic)
}
func (dst *StringTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringTable.Merge(dst, src)
}
func (m *StringTable) XXX_Size() int {
	return xxx_messageInfo_StringTable.Size(m)
}
func (m *StringTable) XXX_DiscardUnknown() {
	xxx_messageInfo_StringTable.DiscardUnknown(m)
}

var xxx_messageInfo_StringTable proto.InternalMessageInfo

func (m *StringTable) GetS() [][]byte {
	if m != nil {
		return m.S
	}
	return nil
}

// Optional metadata that may be included into each primitive.
type Info struct {
	Version   *int32  `protobuf:"varint,1,opt,name=version,def=-1" json:"version,omitempty"`
	Timestamp *int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Changeset *int64  `protobuf:"varint,3,opt,name=changeset" json:"changeset,omitempty"`
	Uid       *int32  `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
	UserSid   *uint32 `protobuf:"varint,5,opt,name=user_sid,json=userSid" json:"user_sid,omitempty"`
	// The visible flag is used to store history information. It indicates that
	// the current object version has been created by a delete operation on the
	// OSM API.
	// When a writer sets this flag, it MUST add a required_features tag with
	// value "HistoricalInformation" to the HeaderBlock.
	// If this flag is not available for some object it MUST be assumed to be
	// true if the file has the required_features tag "HistoricalInformation"
	// set.
	Visible              *bool    `protobuf:"varint,6,opt,name=visible" json:"visible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{5}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (dst *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(dst, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

const Default_Info_Version int32 = -1

func (m *Info) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_Info_Version
}

func (m *Info) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Info) GetChangeset() int64 {
	if m != nil && m.Changeset != nil {
		return *m.Changeset
	}
	return 0
}

func (m *Info) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Info) GetUserSid() uint32 {
	if m != nil && m.UserSid != nil {
		return *m.UserSid
	}
	return 0
}

func (m *Info) GetVisible() bool {
	if m != nil && m.Visible != nil {
		return *m.Visible
	}
	return false
}

// * Optional metadata that may be included into each primitive. Special dense format used in DenseNodes.
type DenseInfo struct {
	Version   []int32 `protobuf:"varint,1,rep,packed,name=version" json:"version,omitempty"`
	Timestamp []int64 `protobuf:"zigzag64,2,rep,packed,name=timestamp" json:"timestamp,omitempty"`
	Changeset []int64 `protobuf:"zigzag64,3,rep,packed,name=changeset" json:"changeset,omitempty"`
	Uid       []int32 `protobuf:"zigzag32,4,rep,packed,name=uid" json:"uid,omitempty"`
	UserSid   []int32 `protobuf:"zigzag32,5,rep,packed,name=user_sid,json=userSid" json:"user_sid,omitempty"`
	// The visible flag is used to store history information. It indicates that
	// the current object version has been created by a delete operation on the
	// OSM API.
	// When a writer sets this flag, it MUST add a required_features tag with
	// value "HistoricalInformation" to the HeaderBlock.
	// If this flag is not available for some object it MUST be assumed to be
	// true if the file has the required_features tag "HistoricalInformation"
	// set.
	Visible              []bool   `protobuf:"varint,6,rep,packed,name=visible" json:"visible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DenseInfo) Reset()         { *m = DenseInfo{} }
func (m *DenseInfo) String() string { return proto.CompactTextString(m) }
func (*DenseInfo) ProtoMessage()    {}
func (*DenseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{6}
}
func (m *DenseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DenseInfo.Unmarshal(m, b)
}
func (m *DenseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DenseInfo.Marshal(b, m, deterministic)
}
func (dst *DenseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenseInfo.Merge(dst, src)
}
func (m *DenseInfo) XXX_Size() int {
	return xxx_messageInfo_DenseInfo.Size(m)
}
func (m *DenseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DenseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DenseInfo proto.InternalMessageInfo

func (m *DenseInfo) GetVersion() []int32 {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *DenseInfo) GetTimestamp() []int64 {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *DenseInfo) GetChangeset() []int64 {
	if m != nil {
		return m.Changeset
	}
	return nil
}

func (m *DenseInfo) GetUid() []int32 {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *DenseInfo) GetUserSid() []int32 {
	if m != nil {
		return m.UserSid
	}
	return nil
}

func (m *DenseInfo) GetVisible() []bool {
	if m != nil {
		return m.Visible
	}
	return nil
}

// THIS IS STUB DESIGN FOR CHANGESETS. NOT USED RIGHT NOW.
// TODO:    REMOVE THIS?
type ChangeSet struct {
	Id                   *int64   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeSet) Reset()         { *m = ChangeSet{} }
func (m *ChangeSet) String() string { return proto.CompactTextString(m) }
func (*ChangeSet) ProtoMessage()    {}
func (*ChangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{7}
}
func (m *ChangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeSet.Unmarshal(m, b)
}
func (m *ChangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeSet.Marshal(b, m, deterministic)
}
func (dst *ChangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeSet.Merge(dst, src)
}
func (m *ChangeSet) XXX_Size() int {
	return xxx_messageInfo_ChangeSet.Size(m)
}
func (m *ChangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeSet proto.InternalMessageInfo

func (m *ChangeSet) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type Node struct {
	Id *int64 `protobuf:"zigzag64,1,req,name=id" json:"id,omitempty"`
	// Parallel arrays.
	Keys                 []uint32 `protobuf:"varint,2,rep,packed,name=keys" json:"keys,omitempty"`
	Vals                 []uint32 `protobuf:"varint,3,rep,packed,name=vals" json:"vals,omitempty"`
	Info                 *Info    `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	Lat                  *int64   `protobuf:"zigzag64,8,req,name=lat" json:"lat,omitempty"`
	Lon                  *int64   `protobuf:"zigzag64,9,req,name=lon" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{8}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Node) GetKeys() []uint32 {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Node) GetVals() []uint32 {
	if m != nil {
		return m.Vals
	}
	return nil
}

func (m *Node) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Node) GetLat() int64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Node) GetLon() int64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

type DenseNodes struct {
	Id []int64 `protobuf:"zigzag64,1,rep,packed,name=id" json:"id,omitempty"`
	// repeated Info info = 4;
	Denseinfo *DenseInfo `protobuf:"bytes,5,opt,name=denseinfo" json:"denseinfo,omitempty"`
	Lat       []int64    `protobuf:"zigzag64,8,rep,packed,name=lat" json:"lat,omitempty"`
	Lon       []int64    `protobuf:"zigzag64,9,rep,packed,name=lon" json:"lon,omitempty"`
	// Special packing of keys and vals into one array. May be empty if all nodes in this block are tagless.
	KeysVals             []int32  `protobuf:"varint,10,rep,packed,name=keys_vals,json=keysVals" json:"keys_vals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DenseNodes) Reset()         { *m = DenseNodes{} }
func (m *DenseNodes) String() string { return proto.CompactTextString(m) }
func (*DenseNodes) ProtoMessage()    {}
func (*DenseNodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{9}
}
func (m *DenseNodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DenseNodes.Unmarshal(m, b)
}
func (m *DenseNodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DenseNodes.Marshal(b, m, deterministic)
}
func (dst *DenseNodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenseNodes.Merge(dst, src)
}
func (m *DenseNodes) XXX_Size() int {
	return xxx_messageInfo_DenseNodes.Size(m)
}
func (m *DenseNodes) XXX_DiscardUnknown() {
	xxx_messageInfo_DenseNodes.DiscardUnknown(m)
}

var xxx_messageInfo_DenseNodes proto.InternalMessageInfo

func (m *DenseNodes) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DenseNodes) GetDenseinfo() *DenseInfo {
	if m != nil {
		return m.Denseinfo
	}
	return nil
}

func (m *DenseNodes) GetLat() []int64 {
	if m != nil {
		return m.Lat
	}
	return nil
}

func (m *DenseNodes) GetLon() []int64 {
	if m != nil {
		return m.Lon
	}
	return nil
}

func (m *DenseNodes) GetKeysVals() []int32 {
	if m != nil {
		return m.KeysVals
	}
	return nil
}

type Way struct {
	Id *int64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	// Parallel arrays.
	Keys                 []uint32 `protobuf:"varint,2,rep,packed,name=keys" json:"keys,omitempty"`
	Vals                 []uint32 `protobuf:"varint,3,rep,packed,name=vals" json:"vals,omitempty"`
	Info                 *Info    `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	Refs                 []int64  `protobuf:"zigzag64,8,rep,packed,name=refs" json:"refs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Way) Reset()         { *m = Way{} }
func (m *Way) String() string { return proto.CompactTextString(m) }
func (*Way) ProtoMessage()    {}
func (*Way) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{10}
}
func (m *Way) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Way.Unmarshal(m, b)
}
func (m *Way) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Way.Marshal(b, m, deterministic)
}
func (dst *Way) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Way.Merge(dst, src)
}
func (m *Way) XXX_Size() int {
	return xxx_messageInfo_Way.Size(m)
}
func (m *Way) XXX_DiscardUnknown() {
	xxx_messageInfo_Way.DiscardUnknown(m)
}

var xxx_messageInfo_Way proto.InternalMessageInfo

func (m *Way) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Way) GetKeys() []uint32 {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Way) GetVals() []uint32 {
	if m != nil {
		return m.Vals
	}
	return nil
}

func (m *Way) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Way) GetRefs() []int64 {
	if m != nil {
		return m.Refs
	}
	return nil
}

type Relation struct {
	Id *int64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	// Parallel arrays.
	Keys []uint32 `protobuf:"varint,2,rep,packed,name=keys" json:"keys,omitempty"`
	Vals []uint32 `protobuf:"varint,3,rep,packed,name=vals" json:"vals,omitempty"`
	Info *Info    `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	// Parallel arrays
	RolesSid             []int32               `protobuf:"varint,8,rep,packed,name=roles_sid,json=rolesSid" json:"roles_sid,omitempty"`
	Memids               []int64               `protobuf:"zigzag64,9,rep,packed,name=memids" json:"memids,omitempty"`
	Types                []Relation_MemberType `protobuf:"varint,10,rep,packed,name=types,enum=OSMPBF.Relation_MemberType" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Relation) Reset()         { *m = Relation{} }
func (m *Relation) String() string { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()    {}
func (*Relation) Descriptor() ([]byte, []int) {
	return fileDescriptor_osmformat_463ab2799bf1d48a, []int{11}
}
func (m *Relation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relation.Unmarshal(m, b)
}
func (m *Relation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relation.Marshal(b, m, deterministic)
}
func (dst *Relation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relation.Merge(dst, src)
}
func (m *Relation) XXX_Size() int {
	return xxx_messageInfo_Relation.Size(m)
}
func (m *Relation) XXX_DiscardUnknown() {
	xxx_messageInfo_Relation.DiscardUnknown(m)
}

var xxx_messageInfo_Relation proto.InternalMessageInfo

func (m *Relation) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Relation) GetKeys() []uint32 {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Relation) GetVals() []uint32 {
	if m != nil {
		return m.Vals
	}
	return nil
}

func (m *Relation) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Relation) GetRolesSid() []int32 {
	if m != nil {
		return m.RolesSid
	}
	return nil
}

func (m *Relation) GetMemids() []int64 {
	if m != nil {
		return m.Memids
	}
	return nil
}

func (m *Relation) GetTypes() []Relation_MemberType {
	if m != nil {
		return m.Types
	}
	return nil
}

func init() {
	proto.RegisterType((*HeaderBlock)(nil), "OSMPBF.HeaderBlock")
	proto.RegisterType((*HeaderBBox)(nil), "OSMPBF.HeaderBBox")
	proto.RegisterType((*PrimitiveBlock)(nil), "OSMPBF.PrimitiveBlock")
	proto.RegisterType((*PrimitiveGroup)(nil), "OSMPBF.PrimitiveGroup")
	proto.RegisterType((*StringTable)(nil), "OSMPBF.StringTable")
	proto.RegisterType((*Info)(nil), "OSMPBF.Info")
	proto.RegisterType((*DenseInfo)(nil), "OSMPBF.DenseInfo")
	proto.RegisterType((*ChangeSet)(nil), "OSMPBF.ChangeSet")
	proto.RegisterType((*Node)(nil), "OSMPBF.Node")
	proto.RegisterType((*DenseNodes)(nil), "OSMPBF.DenseNodes")
	proto.RegisterType((*Way)(nil), "OSMPBF.Way")
	proto.RegisterType((*Relation)(nil), "OSMPBF.Relation")
	proto.RegisterEnum("OSMPBF.Relation_MemberType", Relation_MemberType_name, Relation_MemberType_value)
}

func init() { proto.RegisterFile("osmformat.proto", fileDescriptor_osmformat_463ab2799bf1d48a) }

var fileDescriptor_osmformat_463ab2799bf1d48a = []byte{
	// 1020 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x2d, 0x1f, 0xb2, 0xa5, 0x2b, 0xc7, 0x91, 0x26, 0x86, 0xc1, 0xd4, 0x0e, 0xc2, 0xb2, 0x68,
	0x40, 0xa0, 0x88, 0x22, 0x0b, 0xc8, 0x26, 0x8b, 0x16, 0x51, 0xf3, 0x04, 0x6a, 0x3b, 0x18, 0xbb,
	0x35, 0xba, 0x52, 0x47, 0xe2, 0x48, 0x19, 0x84, 0xe4, 0x28, 0x33, 0x23, 0x27, 0x5a, 0xf5, 0x07,
	0x0a, 0xf4, 0x0f, 0xba, 0xc9, 0xa2, 0xbf, 0xd1, 0x6f, 0xe9, 0x97, 0x14, 0x73, 0x49, 0x8a, 0xb4,
	0x9d, 0x6d, 0xbb, 0xe3, 0x9c, 0x73, 0x78, 0xef, 0x99, 0xfb, 0x20, 0xe1, 0xb6, 0xd4, 0xd9, 0x5c,
	0xaa, 0x8c, 0x99, 0xc1, 0x52, 0x49, 0x23, 0xc9, 0xd6, 0xe9, 0xd9, 0xf1, 0x9b, 0xf1, 0x8b, 0xe8,
	0x93, 0x07, 0xdd, 0x57, 0x9c, 0x25, 0x5c, 0x8d, 0x53, 0x39, 0x7b, 0x47, 0x1e, 0x80, 0x3f, 0x9d,
	0xca, 0x8f, 0x81, 0x13, 0x3a, 0x71, 0x77, 0x44, 0x06, 0x85, 0x6c, 0x50, 0x4a, 0xc6, 0xf2, 0x23,
	0x45, 0x9e, 0x7c, 0x0b, 0x7d, 0xc5, 0xdf, 0xaf, 0x84, 0xe2, 0xc9, 0x64, 0xce, 0x99, 0x59, 0x29,
	0xae, 0x03, 0x3f, 0xf4, 0xe2, 0x0e, 0xed, 0x55, 0xc4, 0x8b, 0x12, 0xb7, 0x62, 0xb9, 0x34, 0x42,
	0xe6, 0x2c, 0xad, 0xc5, 0xad, 0x42, 0x5c, 0x11, 0x1b, 0xf1, 0x03, 0xd8, 0xfd, 0xa0, 0x84, 0x11,
	0xf9, 0x62, 0xa9, 0xe4, 0x42, 0xb1, 0x2c, 0xe8, 0x85, 0x4e, 0xdc, 0xa1, 0xd7, 0x50, 0xb2, 0x0f,
	0x5b, 0x5a, 0xae, 0xd4, 0x8c, 0x07, 0x7d, 0xe4, 0xcb, 0x13, 0x19, 0xc3, 0x3d, 0xa9, 0x33, 0xa9,
	0x85, 0x9e, 0x28, 0xbe, 0x4c, 0xc5, 0x8c, 0xd9, 0x04, 0x13, 0x23, 0x32, 0xae, 0x0d, 0xcb, 0x96,
	0x41, 0x18, 0x3a, 0xb1, 0x47, 0x0f, 0x4a, 0x11, 0xad, 0x35, 0xe7, 0x95, 0x84, 0x1c, 0xc3, 0xd7,
	0x9f, 0x8b, 0xa1, 0xf9, 0xfb, 0x15, 0xcf, 0x67, 0x7c, 0x92, 0xaf, 0xb2, 0x29, 0x57, 0xc1, 0x57,
	0x18, 0x29, 0xbc, 0x19, 0xe9, 0xac, 0x14, 0x9e, 0xa0, 0x8e, 0x7c, 0x0f, 0x87, 0x9f, 0x0b, 0x37,
	0x65, 0x9a, 0x4f, 0x56, 0x2a, 0x0d, 0x22, 0xbc, 0xc0, 0xdd, 0x9b, 0x71, 0xc6, 0x4c, 0xf3, 0x9f,
	0x54, 0x1a, 0xfd, 0x0a, 0x50, 0x77, 0x80, 0x10, 0xf0, 0x53, 0x3e, 0x37, 0x81, 0x13, 0xba, 0x31,
	0xa1, 0xf8, 0x4c, 0xf6, 0xa0, 0xa5, 0xc4, 0xe2, 0xad, 0x09, 0x5c, 0x04, 0x8b, 0x03, 0xe9, 0x81,
	0x67, 0xe4, 0x32, 0xf0, 0x10, 0xb3, 0x8f, 0xb6, 0x6a, 0x53, 0x69, 0x8c, 0xcc, 0x02, 0x1f, 0xc1,
	0xf2, 0x14, 0x7d, 0x72, 0x61, 0xf7, 0x8d, 0x12, 0x99, 0x30, 0xe2, 0x92, 0x17, 0xa3, 0xf0, 0x18,
	0xba, 0xda, 0x28, 0x91, 0x2f, 0x0c, 0x9b, 0xa6, 0x1c, 0xb3, 0x75, 0x47, 0x77, 0xaa, 0x89, 0x38,
	0x43, 0xea, 0xdc, 0x52, 0xb4, 0xa9, 0x23, 0xdf, 0xc1, 0xee, 0xb2, 0x0a, 0xb4, 0x50, 0x72, 0xb5,
	0x0c, 0xdc, 0xd0, 0x8b, 0xbb, 0xa3, 0xfd, 0xea, 0xcd, 0x4d, 0x9a, 0x97, 0x96, 0xa5, 0xd7, 0xd4,
	0xe4, 0x1b, 0xe8, 0x2e, 0x14, 0xcb, 0x57, 0x29, 0x53, 0xc2, 0xac, 0xb1, 0xb9, 0xad, 0x27, 0xde,
	0xd1, 0x70, 0x48, 0x9b, 0x38, 0x09, 0x01, 0x52, 0x66, 0x26, 0x72, 0x3e, 0xd7, 0xdc, 0x04, 0x77,
	0x6c, 0x27, 0x9e, 0x38, 0x43, 0xda, 0x49, 0x99, 0x39, 0x45, 0x0c, 0x15, 0x32, 0xaf, 0x14, 0x7b,
	0xb5, 0x42, 0xe6, 0xa5, 0xe2, 0x11, 0xf4, 0x12, 0x66, 0xf8, 0xa4, 0x99, 0x8f, 0x60, 0x3e, 0xff,
	0x68, 0x38, 0x1c, 0xd2, 0xdb, 0x96, 0x7d, 0x59, 0x93, 0xd1, 0x3f, 0x4e, 0xa3, 0x4a, 0x68, 0x9f,
	0x44, 0xd0, 0xca, 0x65, 0xc2, 0x75, 0xe0, 0xe0, 0x2d, 0x77, 0xaa, 0x5b, 0x9e, 0xc8, 0x84, 0xd3,
	0x82, 0x22, 0x31, 0xb4, 0x12, 0x9e, 0x6b, 0x1e, 0xb8, 0x57, 0xb7, 0xea, 0x99, 0x05, 0xad, 0x50,
	0xd3, 0x42, 0x40, 0xee, 0x83, 0xff, 0x81, 0xad, 0x75, 0xe0, 0x61, 0xb0, 0x6e, 0x25, 0xbc, 0x60,
	0x6b, 0x8a, 0x04, 0x19, 0x40, 0x47, 0xf1, 0x14, 0x87, 0xa3, 0xd8, 0xb7, 0xee, 0xa8, 0x57, 0xa9,
	0x68, 0x49, 0xd0, 0x5a, 0x42, 0x8e, 0x00, 0x66, 0x6f, 0x59, 0xbe, 0xe0, 0x9a, 0x9b, 0x62, 0xe7,
	0xba, 0xa3, 0x7e, 0xf5, 0xc2, 0x0f, 0xc8, 0x9c, 0x71, 0x43, 0x1b, 0xa2, 0xe8, 0x00, 0xba, 0x8d,
	0xe6, 0x92, 0x1d, 0x70, 0x8a, 0xcb, 0xed, 0x50, 0x47, 0x47, 0x7f, 0x39, 0xe0, 0xbf, 0xce, 0xe7,
	0x92, 0x1c, 0xc2, 0xf6, 0x25, 0x57, 0x5a, 0xc8, 0x1c, 0xbf, 0x15, 0xad, 0x27, 0xee, 0xc3, 0x23,
	0x5a, 0x41, 0xe4, 0x10, 0x3a, 0xf5, 0xc2, 0xb9, 0xb8, 0x26, 0x35, 0x60, 0xd9, 0x4d, 0xbe, 0xc0,
	0x2b, 0xd8, 0x0d, 0x60, 0x87, 0x76, 0x25, 0x92, 0xc0, 0xb7, 0x51, 0xa9, 0x7d, 0x24, 0x77, 0xa1,
	0xbd, 0xd2, 0x5c, 0x4d, 0xb4, 0x48, 0x82, 0x56, 0xe8, 0xc4, 0xb7, 0xe8, 0xb6, 0x3d, 0x9f, 0x89,
	0x84, 0x04, 0xb0, 0x7d, 0x29, 0xb4, 0xb0, 0x03, 0xba, 0x15, 0x3a, 0x71, 0x9b, 0x56, 0xc7, 0xe8,
	0x6f, 0x07, 0x3a, 0x58, 0xe0, 0x9b, 0x76, 0xbd, 0xb8, 0x35, 0x76, 0x7b, 0x4e, 0x6d, 0x37, 0xbc,
	0x6a, 0xd7, 0x8b, 0x09, 0xf2, 0x0d, 0xcb, 0xe1, 0x55, 0xcb, 0x1b, 0x45, 0x6d, 0x7b, 0xaf, 0xb2,
	0xed, 0xc5, 0x7d, 0xe4, 0xd0, 0xfa, 0xbd, 0x2b, 0xd6, 0x2b, 0x6a, 0x63, 0xff, 0xb0, 0x69, 0xdf,
	0x8b, 0xdb, 0xa5, 0xad, 0xf2, 0x0a, 0x07, 0xd0, 0xd9, 0xb4, 0x88, 0xec, 0x82, 0x2b, 0x12, 0xdc,
	0x42, 0x8f, 0xba, 0x22, 0x89, 0x7e, 0x77, 0xc0, 0xb7, 0xb3, 0xd3, 0x20, 0x88, 0x25, 0xc8, 0x3e,
	0xf8, 0xef, 0xf8, 0x5a, 0xe3, 0x3d, 0x6e, 0x61, 0x40, 0x3c, 0x5b, 0xfc, 0x92, 0xa5, 0xc5, 0x6c,
	0x95, 0xb8, 0x3d, 0x93, 0x10, 0x7c, 0x91, 0xcf, 0x25, 0x16, 0xbc, 0x31, 0xc0, 0xb6, 0x6c, 0x14,
	0x19, 0xdb, 0x91, 0x94, 0x99, 0xa0, 0x5d, 0x7c, 0x46, 0x52, 0x86, 0x3d, 0x4a, 0x65, 0x1e, 0x74,
	0x4a, 0x44, 0xe6, 0xd1, 0x9f, 0x0e, 0x40, 0x3d, 0xcf, 0x84, 0x94, 0xa6, 0xaa, 0x42, 0x59, 0x63,
	0x8f, 0xa0, 0x83, 0x53, 0x8e, 0xd9, 0x5a, 0x98, 0xad, 0x7f, 0x65, 0x15, 0x30, 0x65, 0xad, 0xb1,
	0x25, 0x2d, 0xf2, 0x56, 0x51, 0x30, 0xf7, 0x5e, 0x95, 0xbb, 0x46, 0x65, 0x4e, 0xee, 0x43, 0xc7,
	0xde, 0x72, 0x82, 0x57, 0x84, 0x4d, 0x8b, 0xdb, 0x16, 0xfc, 0x99, 0xa5, 0x3a, 0xfa, 0x0d, 0xbc,
	0x0b, 0xb6, 0xbe, 0x5e, 0xc6, 0xff, 0xa0, 0x5a, 0xfb, 0xe0, 0x2b, 0x3e, 0xd7, 0x0d, 0xdb, 0x78,
	0x8e, 0xfe, 0x70, 0xa1, 0x5d, 0xad, 0xe8, 0xff, 0x60, 0xe3, 0x3e, 0x74, 0x94, 0x4c, 0xb9, 0xc6,
	0xd1, 0x6b, 0xd7, 0x05, 0x41, 0xd0, 0xce, 0xde, 0x97, 0xb0, 0x95, 0xf1, 0x4c, 0x24, 0xba, 0x51,
	0xca, 0x12, 0x21, 0x8f, 0xa1, 0x65, 0xd6, 0x4b, 0x5e, 0x54, 0x72, 0x77, 0x74, 0x70, 0xfd, 0x13,
	0x33, 0x38, 0xe6, 0xf6, 0xcf, 0x76, 0xbe, 0x5e, 0x72, 0x7c, 0xaf, 0x50, 0x47, 0x0f, 0x01, 0x6a,
	0x82, 0xb4, 0xc1, 0x3f, 0x39, 0x7d, 0xf6, 0xbc, 0xf7, 0x05, 0xd9, 0x06, 0xef, 0xe2, 0xe9, 0x2f,
	0x3d, 0x87, 0xec, 0x40, 0x9b, 0x3e, 0xff, 0xf1, 0xe9, 0xf9, 0xeb, 0xd3, 0x93, 0x9e, 0x3b, 0xee,
	0xc3, 0xad, 0x99, 0x92, 0x7a, 0xba, 0x1e, 0x4c, 0x45, 0xce, 0xd4, 0xfa, 0x95, 0xf7, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x47, 0x36, 0x54, 0x88, 0xa9, 0x08, 0x00, 0x00,
}
